// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task.App.DataBaseContext;

#nullable disable

namespace Test.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task.App.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payroll")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a815e489-caab-42de-86a5-5d2a5b7c298c"),
                            Address = "12 Foreman road",
                            Address2 = "London",
                            DateOfBirth = "26/01/1955",
                            Email = "nomadic20@hotmail.co.uk",
                            Forename = "John ",
                            Mobile = "987654231",
                            Payroll = "COOP08",
                            PostCode = "GU12 6JW",
                            StartDate = "18/04/2013",
                            Surname = "William",
                            Telephone = "12345678"
                        },
                        new
                        {
                            Id = new Guid("5d4e6479-6a42-485b-bec9-aa560fa31cdd"),
                            Address = "115 Spinney Road",
                            Address2 = "Luton",
                            DateOfBirth = "11/5/1974",
                            Email = "gerry.jackson@bt.com",
                            Forename = "Jerry",
                            Mobile = "6987457",
                            Payroll = "JACK13",
                            PostCode = "LU33DF",
                            StartDate = "18/04/2013",
                            Surname = "Jackson",
                            Telephone = "2050508"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
